version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb3
    ports:
      - 27019:27017
    volumes:
      - mongo-data3:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis3
    ports:
      - 6379:6379
    networks:
      - app_network
volumes:
  mongo-data3: {}

networks:
  app_network:
    driver: bridge